+incdir+../../core
../../peripheral/ram/GTP_DRM18K_model.v
../../peripheral/ram/pango/IRAM_init_param.v
../../peripheral/ram/pango/ipml_dpram_v1_8_IRAM.v
../../peripheral/ram/pango/IRAM.v
../../peripheral/ram/pango/SRAM_init_param.v
../../peripheral/ram/pango/ipml_dpram_v1_8_SRAM.v
../../peripheral/ram/pango/SRAM.v
../../core/defines.v
../../core/dff.v
../../core/regfiles.v
../../core/PC_control.v
../../core/Ifu.v
../../core/idec.v
../../core/exu_common.v
../../core/exu_bjp.v
../../core/exu_muldiv.v
../../core/exu_ls.v
../../core/ls_ctrl.v
../../core/wb_arbiter.v
../../core/disp_exu.v
../../core/core.v
../../peripheral/ram/sram.v
../../peripheral/uart/uart_tx.v
../../peripheral/uart/uart_rx.v
../../peripheral/uart/uart.v
../../peripheral/uart/uart_axi_lite_wrapper.v
../../peripheral/timer/timer.v
../../peripheral/sys_pll_sim.v
../../peripheral/AXI_Interconnect.v
../../peripheral/soc_top.v
tb_ls_ctrl_unaligned.sv
tb_exu_ls_issue.sv
tb_soc_program.sv
