#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Wed Mar 25 12:02:28 2026

set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module SoC_Top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module SoC_Top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_design E:/FPGA/TSP_RVmaster/FPGA/pango_cpu/ipcore/RAM/RAM.idf
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module SoC_Top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module SoC_Top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module SoC_Top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
